// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVnM2ywYD8oKfopHmSy_l_hP9afJHJq_Q',
    appId: '1:872337585161:web:e209443dd955b815dbb4d8',
    messagingSenderId: '872337585161',
    projectId: 'gpt-app-79bbc',
    authDomain: 'gpt-app-79bbc.firebaseapp.com',
    storageBucket: 'gpt-app-79bbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIuimFW_KoyJnU3q3hIfJgdtjHFaJIjEo',
    appId: '1:872337585161:android:04245a4721e756bddbb4d8',
    messagingSenderId: '872337585161',
    projectId: 'gpt-app-79bbc',
    storageBucket: 'gpt-app-79bbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBP4We3k-k9c5Kw9dx3qvAqR3bk2b4Uc',
    appId: '1:872337585161:ios:2c59e95417e72df3dbb4d8',
    messagingSenderId: '872337585161',
    projectId: 'gpt-app-79bbc',
    storageBucket: 'gpt-app-79bbc.appspot.com',
    iosClientId: '872337585161-n88mkqhu3e5p1774gegpc07i738naug5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyBP4We3k-k9c5Kw9dx3qvAqR3bk2b4Uc',
    appId: '1:872337585161:ios:2c59e95417e72df3dbb4d8',
    messagingSenderId: '872337585161',
    projectId: 'gpt-app-79bbc',
    storageBucket: 'gpt-app-79bbc.appspot.com',
    iosClientId: '872337585161-n88mkqhu3e5p1774gegpc07i738naug5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptApp',
  );
}
